[build]
  base = "animehub-frontend"
  command = "CI=false npm install && npm run lint && npm run build"
  publish = "build"

[build.environment]
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 